// Auto-generated by `scripts/generate-tiles.mjs`. Do not edit by hand.
import type { TileMeta } from './types';

export const TILE_META: TileMeta = {
  width: 5944,
  height: 8075,
  maxZoom: 3,
  tileSize: 256,
};
