#!/usr/bin/env node
/**
 * Generate Leaflet CRS.Simple tile pyramid for the GTA V map.
 *
 * Usage: node scripts/generate-tiles.mjs
 *
 * Inputs:
 *   docs/clean-map.jpg   (blind map without labels — preferred for blind quizzes)
 *
 * Outputs:
 *   public/tiles/{z}/{x}/{y}.jpg     (z=0..MAX_ZOOM, JPEG q=80, 256x256)
 *   src/modules/geo/data/tileMeta.ts (overwritten with computed dimensions)
 *
 * Re-run when the source image changes.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(ROOT, 'docs', 'clean-map.jpg');
const OUT_DIR = path.join(ROOT, 'public', 'tiles');
const META_OUT = path.join(ROOT, 'src', 'modules', 'geo', 'data', 'tileMeta.ts');

const TILE_SIZE = 256;
const MAX_ZOOM = 3;
const JPEG_QUALITY = 80;
const BG = { r: 14, g: 50, b: 69, alpha: 1 }; // sasp-bg-ish background fill for letterbox

async function main() {
  console.log(`Source: ${SOURCE}`);
  const meta = await sharp(SOURCE).metadata();
  if (!meta.width || !meta.height) {
    throw new Error('Could not read source dimensions');
  }
  const W = meta.width;
  const H = meta.height;
  console.log(`Source dimensions: ${W} x ${H}`);

  // Wipe existing tiles to avoid stale ones if dimensions changed.
  await fs.rm(OUT_DIR, { recursive: true, force: true });
  await fs.mkdir(OUT_DIR, { recursive: true });

  // For each zoom level: figure out the displayed image size, render to that size on a
  // letterboxed background, then slice into tiles.
  // CRS.Simple convention: zoom 0 has 1 tile worth of "natural" coverage; the bounds we'll
  // use in Leaflet are [[0, 0], [H, W]] (source-pixel space), and the tile layer renders
  // bounds-aligned tiles. We pre-rasterize each zoom's image so the source maps to that
  // zoom's tile grid exactly.

  let totalTiles = 0;
  for (let z = 0; z <= MAX_ZOOM; z++) {
    const scale = Math.pow(2, z);
    // tilesAcross/tilesDown: how many tiles cover the image at this zoom (ceil).
    const tilesAcross = Math.ceil((W * scale) / (W * 1)); // placeholder; recomputed below
    void tilesAcross;
    // We pick zoomedWidth so that source pixel (W,H) maps cleanly. Approach:
    //  - At z=MAX_ZOOM, zoomedWidth = W (native pixels).
    //  - At z<MAX_ZOOM, zoomedWidth = W / 2^(MAX_ZOOM - z) (downscaled).
    const zoomedW = Math.round(W / Math.pow(2, MAX_ZOOM - z));
    const zoomedH = Math.round(H / Math.pow(2, MAX_ZOOM - z));
    const cols = Math.ceil(zoomedW / TILE_SIZE);
    const rows = Math.ceil(zoomedH / TILE_SIZE);
    const canvasW = cols * TILE_SIZE;
    const canvasH = rows * TILE_SIZE;
    console.log(
      `z=${z}: ${zoomedW}x${zoomedH} on ${canvasW}x${canvasH} canvas → ${cols}x${rows} = ${cols * rows} tiles`,
    );

    const buf = await sharp(SOURCE)
      .resize(zoomedW, zoomedH, { kernel: sharp.kernel.lanczos3 })
      .extend({
        top: 0,
        left: 0,
        bottom: canvasH - zoomedH,
        right: canvasW - zoomedW,
        background: BG,
      })
      .toFormat('jpeg', { quality: JPEG_QUALITY })
      .toBuffer();

    const baseImg = sharp(buf);

    for (let row = 0; row < rows; row++) {
      for (let col = 0; col < cols; col++) {
        const tileBuf = await baseImg
          .clone()
          .extract({
            left: col * TILE_SIZE,
            top: row * TILE_SIZE,
            width: TILE_SIZE,
            height: TILE_SIZE,
          })
          .toBuffer();
        const dir = path.join(OUT_DIR, String(z), String(col));
        await fs.mkdir(dir, { recursive: true });
        await fs.writeFile(path.join(dir, `${row}.jpg`), tileBuf);
        totalTiles++;
      }
    }
  }

  // Write meta TS file
  const tsContent = `// Auto-generated by \`scripts/generate-tiles.mjs\`. Do not edit by hand.
import type { TileMeta } from './types';

export const TILE_META: TileMeta = {
  width: ${W},
  height: ${H},
  maxZoom: ${MAX_ZOOM},
  tileSize: ${TILE_SIZE},
};
`;
  await fs.writeFile(META_OUT, tsContent);
  console.log(`Wrote ${META_OUT}`);
  console.log(`Done. Generated ${totalTiles} tiles into ${OUT_DIR}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
